name: Build Test Unit.js

on:
  push:  
    branches: [main]
  pull_request: 
     branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd ServerRest && npm ci && npm run test:unit

      
