name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build ServerRest --file ServerRest/Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Run Docker Container
      run: docker run -p 3000:3000 paulogoncalvesbh/serverest:latest
     
    - name: Run K6
      run: cd ServerRest && k6 run test/performance/index.js
