name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ServerRest --file ServerRest/Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/setup-node@v4
    - name: Intalation Node
      run: cd ServerRest && npm ci && npm run test:unit
    - uses: actions/setup-node@v4
    - name: Run K6
      run: cd ServerRest && npm ci && npm run k6 index.js
      
