name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Testes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: List files
      run: ls -la
      
    - name: Instalar dependências
      run: npm ci --production --ignore-scripts
      working-directory: ./ServerRest
    
    - name: Construir imagem Docker
      run: docker build -f ./ServerRest/Dockerfile .
      
    - name: Executar container Docker (em segundo plano)
      run: docker run -d --name my-app -p 3000:3000 my-app:latest
    
    - uses: actions/setup-node@v4
        
    - name: Run K6
      run: cd ServerRest && k6 run test/performance/index.js

      # (Opcional) Parar e remover o container ao final do job
    - name: Cleanup
      if: always()
      run: docker rm -f my-app || true
