name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  TESTES:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ServerRest --file ServerRest/Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/setup-node@v4
    - name: Unit Test
      run: cd ServerRest && npm ci && npm run test:unit
    - name: Install K6
      run: sudo apt-get update && sudo apt-get install -y k6
    - name: Run K6
      run: cd ServerRest && k6 run index.js
      
